In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np
import requests

from pprint import pprint

# Filenames (CSV)
i_filename = "city_weather_data.csv"
o_filename = "city_weather_data_concise.csv"

In [4]:
c_df = pd.read_csv(i_filename, header=0)

In [5]:
c_df.head()

,City Name,Country Name,Country Official Name,Country Code,Target Lat,Target Long,Grid Lat,Grid Long,Actual Lat,Actual Long,In Target Grid Area,Temp,Humidity,Cloudiness,Wind Speed,Wind Direction,Weather Description,Weather Icon URL
0,Vaini,Tonga,Kingdom of Tonga,TO,-87.403023,-178.622696,-90.0,-180.0,-21.20,-175.20,False,75.20,88.0,90.0,12.75,130.000,overcast clouds,http://openweathermap.org/img/w/04n.png
1,Rikitea,French Polynesia,French Polynesia,PF,-90.000000,-137.392917,-90.0,-138.0,-23.12,-134.97,False,71.38,100.0,92.0,3.60,138.001,light rain,http://openweathermap.org/img/w/10d.png
2,Punta Arenas,Chile,Republic of Chile,CL,-90.000000,-126.899912,-90.0,-124.0,-53.16,-70.91,False,50.00,46.0,20.0,28.86,250.000,few clouds,http://openweathermap.org/img/w/02d.png
3,Ushuaia,Argentina,Argentine Republic,AR,-90.000000,-88.965214,-90.0,-89.0,-54.81,-68.31,False,44.60,70.0,75.0,34.45,230.000,shower rain,http://openweathermap.org/img/w/09d.png
4,Hermanus,South Africa,Republic of South Africa,ZA,-90.000000,-8.711752,-90.0,-12.0,-34.42,19.24,False,74.40,53.0,36.0,7.85,240.501,scattered clouds,http://openweathermap.org/img/w/03d.png

In [7]:
c_df.columns

Index(['City Name', 'Country Name', 'Country Official Name', 'Country Code',
       'Target Lat', 'Target Long', 'Grid Lat', 'Grid Long', 'Actual Lat',
       'Actual Long', 'In Target Grid Area', 'Temp', 'Humidity', 'Cloudiness',
       'Wind Speed', 'Wind Direction', 'Weather Description',
       'Weather Icon URL'],
      dtype='object')

In [14]:
o_columns = ['City Name', 'Country Code',
                'Actual Lat', 'Actual Long',
                'Temp', 'Humidity', 'Cloudiness', 'Wind Speed']

In [16]:
c_df[o_columns].head(10)

,City Name,Country Code,Actual Lat,Actual Long,Temp,Humidity,Cloudiness,Wind Speed
0,Vaini,TO,-21.20,-175.20,75.20,88.0,90.0,12.75
1,Rikitea,PF,-23.12,-134.97,71.38,100.0,92.0,3.60
2,Punta Arenas,CL,-53.16,-70.91,50.00,46.0,20.0,28.86
3,Ushuaia,AR,-54.81,-68.31,44.60,70.0,75.0,34.45
4,Hermanus,ZA,-34.42,19.24,74.40,53.0,36.0,7.85
5,Bredasdorp,ZA,-34.53,20.04,80.60,47.0,88.0,24.16
6,Kruisfontein,ZA,-34.00,24.73,69.09,77.0,0.0,18.14
7,Port Elizabeth,ZA,-33.92,25.57,73.40,73.0,75.0,19.46
8,Port Alfred,ZA,-33.59,26.89,72.55,83.0,76.0,15.57
9,Busselton,AU,-33.64,115.35,68.28,100.0,0.0,17.25

In [18]:
c_df[o_columns].to_csv(o_filename, index_label='City ID')